; ============================
; MACHINE B - extensions.conf
; PJSIP PUR
; ============================

[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
CONSOLE=Console/dsp

; ==================================================
; CONTEXTE LOCAL
; Appels INITIÉS depuis Linphone B
; ==================================================

[internal]

; --- Tests ---
exten => 600,1,Playback(demo-echotest)
 same => n,Echo
 same => n,Playback(demo-echodone)
 same => n,Hangup()

exten => 1337,1,Answer()
 same => n,Playback(tt-weasels)
 same => n,Hangup()

; --- Linphone B -> GSM distant (MSC A) ---
exten => _9XXXXX,1,NoOp(B -> GSM distant A)
 same => n,Dial(PJSIP/${EXTEN:1}@remote_ast)
 same => n,Hangup()

; --- Linphone B -> Linphone A ---
exten => 100,1,NoOp(B -> Linphone A)
 same => n,Dial(PJSIP/100@remote_ast)
 same => n,Hangup()


; ==================================================
; APPELS ENTRANTS DEPUIS A (SIP/PJSIP)
; ==================================================

[from_remote]

; --- A -> Linphone B ---
exten => 100,1,NoOp(A -> Linphone B)
 same => n,Dial(PJSIP/linphone_B)
 same => n,Hangup()

; --- A -> GSM local B ---
exten => _XXXXX,1,NoOp(A -> GSM local B)
 same => n,Dial(PJSIP/${EXTEN}@osmo_msc)
 same => n,Hangup()


; ==================================================
; GSM ENTRANT (MSC LOCAL B via SIP)
; ==================================================

[gsm_subscriber]

; --- GSM -> Linphone B ---
exten => 100,1,NoOp(GSM B -> Linphone B)
 same => n,Dial(PJSIP/linphone_B)
 same => n,Hangup()

; --- GSM -> Dispatch ---
exten => _XXXXX,1,NoOp(GSM entrant local B)
 same => n,Goto(gsm_dispatch,${EXTEN},1)


; ==================================================
; DISPATCH GSM (POLITIQUE GSM)
; ==================================================

[gsm_dispatch]

; --- GSM B -> GSM A ---
exten => _XXXXX,1,NoOp(GSM B -> GSM A)
 same => n,Dial(PJSIP/${EXTEN}@remote_ast)
 same => n,Hangup()
