---
showSupportUrl:      false
showKnownIssuesUrl:  false
showReleaseNotesUrl: false
requirements:
    requiredStorage:  12
    requiredRam:      2
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - root
