#!/bin/sh

if [ $# -lt 1 ]
then
	echo "usage: $0 from-number [options]" 1>&2
	exit 1
fi

echo "user-addr $1"
shift

while [ $# != 0 ]
do
	case "$1" in
		lp|mms|rp|sr)
			echo "$1"
			shift
			;;
		pid|sc-ts)
			if [ $# -lt 2 ]
			then
				echo "error: $1 requires an argument" 1>&2
				exit 1
			fi
			echo "$1 $2"
			shift
			shift
			;;
		*)
			echo "error: invalid option $1" 1>&2
			exit 1
	esac
done
