[general]
static=yes
writeprotect=no

[globals]
CONSOLE=Console/dsp

[internal]
exten => 600,1,Playback(demo-echotest)
exten => 600,n,Echo
exten => 600,n,Playback(demo-echodone)
exten => 600,n,Goto(s,6)

exten => 1337,1,Answer()
exten => 1337,n,Playback(tt-weasels)
exten => 1337,n,Hangup()

; 5 chiffres -> trunk GSM (endpoint = GSM)
exten => _XXXXX,1,Dial(PJSIP/${EXTEN}@GSM)
exten => _XXXXX,n,Playback(vm-nobodyavail)
exten => _XXXXX,n,Hangup()

; Vers le client GSM 2 via IAX2
exten => 300,1,NoOp(Appel vers IAX2 GSM client 2)
 same => n,Dial(IAX2/gsmclient1@192.168.1.101/100,30)
 same => n,Hangup()

; Vers Linphone (désormais configuré en IAX2)
exten => 200,1,NoOp(Vers Linphone B en IAX2)
 same => n,Dial(PJSIP/linphone_B@192.168.1.162,30)
 same => n,Hangup()

exten => 300,1,NoOp(Appel vers IAX2 GSM client 2)
 same => n,Dial(IAX2/gsmclient2@192.168.1.162/100,30)
 same => n,Hangup()


[gsmsubscriber]

; Vers Linphone (désormais configuré en IAX2)
exten => 101,1,NoOp(Vers Linphone A en IAX2)
 same => n,Dial(PJSIP/linphone_A@192.168.1.101,30)
 same => n,Hangup()

---

; --- Node B (192.168.1.162) ---

; Vers le client GSM 2 via IAX2
exten => 201,1,NoOp(Appel vers IAX2 GSM client 2)
 same => n,Dial(IAX2/gsmclient2@192.168.1.162,30)
 same => n,Hangup()

; Vers Linphone (désormais configuré en IAX2)
exten => 301,1,NoOp(Vers Linphone B en IAX2)
 same => n,Dial(PJSIP/linphone_B@192.168.1.162,30)
 same => n,Hangup()
