[general]
bindport=4569
bindaddr=0.0.0.0
disallow=all
allow=gsm
allow=ulaw

[gsmclient1]
type=friend
password=mybigsecret
host=192.168.1.101
context=gsmsubscriber
trunk=yes
qualify=yes

[gsmclient2]
type=friend
password=mybigsecret
host=192.168.1.162
context=gsmsubscriber
trunk=yes
qualify=yes

