; ============================
; /etc/asterisk/pjsip.conf
; ============================

[global]
type=global
user_agent=TP-Asterisk-PJSIP

; ============================
; Transport SIP (UDP 5060)
; ============================

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=192.168.1.101
external_media_address=192.168.1.101


; ==================================================
; UTILISATEUR SIP : Linphone (linphone_A)
; ==================================================

[linphone_A]
type=endpoint
transport=transport-udp
context=internal
disallow=all
allow=ulaw
allow=gsm

auth=linphone_A
aors=linphone_A

direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes


[linphone_A]
type=auth
auth_type=userpass
username=linphone_A
password=tester


[linphone_A]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=30


